on:
  push:

jobs:
  # CI
  display-location:
    name: display location
    runs-on: ubuntu-latest
    steps:
      - name: display
        run: pwd

  # CI
  build-deploy:
    name: build deploy
    runs-on: ubuntu-latest
    needs: display-location
    steps:
      # CI
      - uses: actions/checkout@v4
      - name: build with nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      ## Lint
      - run: npm ci
      - run: npm run build --if-present
      - name: display dist
        run: ls -al
      # TU
      # Analyse sonar
      # copier livrable dans nexus

      # CD
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PRIVATE_KEY }}
          source: 'dist/*'
          target: '/var/www/html/'
